#!/bin/bash
#simple script for logging out via a terminal emulator
read -p "Are you sure you want to log out, $USER? [y/n]: " response
while true; do
    if [ "${response,,}" = "y" ]; then
	pkill -u $USER
	break
    elif [ "${response,,}" = "n" ]; then
	break
    else
	read -p "Invalid response. Please enter either a 'y' or an 'n': " response
    fi
done
